# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20180619_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=30)),
                ('CONTENT', models.TextField(null=True)),
            ],
        ),
    ]
