# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20180705_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
