# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_delete_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cc_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
