# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_profile_cc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cc_no',
            field=models.CharField(max_length=30),
        ),
    ]
