# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_profile_ldate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ldate',
        ),
    ]
