# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_hearing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hearing',
            old_name='lst',
            new_name='lstdate',
        ),
        migrations.RenameField(
            model_name='hearing',
            old_name='nxt',
            new_name='nxtdate',
        ),
    ]
