# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_auto_20180716_1758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hearing',
        ),
        migrations.AddField(
            model_name='profile',
            name='lstdate',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nxtdate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
